trigger:
  branches:
    include:
      - main
      - dev

pr:
  drafts: false
  branches:
    include:
      - dev
      - main
      - feature/*
      - fix/*

pool:
  name: default

stages:
  - stage: CodeQualityCheck
    jobs:
      - job: QualityCheck
        steps:
          - checkout: self
          - script: echo "Code quality is checked"
            displayName: Code Quality Check

  - stage: RuffCheck
    jobs:
      - job: RuffLint
        steps:
          - checkout: self
          - script: echo "Ruff is completed"
            displayName: Ruff Linter
