trigger:
  branches:
    include:
      - main
      # - dev

pr:
  drafts: true
  branches:
    include:
      - dev
      - main
      - feature/*
      - fix/*

resources:
  repositories:
    - repository: templates
      type: github
      name: saikumar1207-p/dso_azure_pipeline_templates
      ref: refs/heads/main  
      endpoint: saikumar1207-p

pool:
  name: default

stages:
  - stage: CodeQuality
    jobs:
      - job: QualityCheck
        steps:
          - checkout: self
          - script: echo "Code quality is checked"
            displayName: Code Quality Check

  - stage: RuffCheck
    dependsOn: CodeQuality
    jobs:
      - job: RuffLint
        steps:
          - checkout: self
          - script: echo "Ruff is completed"
            displayName: Ruff Linter

  - stage: Tests
    dependsOn: RuffCheck
    jobs:
      - job: UnitTests
        steps:
          - checkout: self
          - template: tests/unittest.yml@templates  # Correct path and repo alias
            parameters:
              package: test-ursgal
              testFolder: tests/unittests
              testCategory: Unittests
              pythonVersion: 3.9
          - script: echo "Unit testing is completed"
            displayName: Unit Testing

      - job: IntegrationTests
        steps:
          - checkout: self
          - script: echo "Integration testing is completed"
            displayName: Integration Testing
