trigger:
  branches:
    include:
      - main
      - dev

pr:
  drafts: false
  branches:
    include:
      - dev
      - main
      - feature/*
      - fix/*

pool:
  name: default

stages:
  - stage: CodeQuality
    jobs:
      - job: QualityCheck
        steps:
          - checkout: self
          - script: echo "Code quality is checked"
            displayName: Code Quality Check

  - stage: RuffCheck
    dependsOn: CodeQuality
    jobs:
      - job: RuffLint
        steps:
          - checkout: self
          - script: echo "Ruff is completed"
            displayName: Ruff Linter

  - stage: Tests
    dependsOn: RuffCheck
    jobs:
      - job: UnitTests
        steps:
          - checkout: self
          - script: echo "Unit testing is completed"
            displayName: Unit Testing

      - job: IntegrationTests
        steps:
          - checkout: self
          - script: echo "Integration testing is completed"
            displayName: Integration Testing
