trigger:
  branches:
    include:
      - main
      - dev
      
pr:
  drafts: false
  branches:
    include:
      - dev
      - main
      - feature/*
      - fix/*
      
pool:
  name: 'default'
Stages:
  - stage: code Quality Check
      echo "code Quality is Checked"
  - stage: Ruff
      echo "Ruff Is Completed"    
steps:
  - checkout: self

  - script: echo "Hello, this is a basic script step"
    displayName: "Run Script"      
